### ISSUE TITLE
Question - passing/setting/injecting objects within a plugin namespace

### ISSUE THREAD

**Issue by emeraldjava** [davilera/WordPress-Plugin-Boilerplate-with-PSR-4#1]
Hi,

Thanks for this great project. I'm upgrading an existing plugin to use this structure. I'm wondering can you advise on the best practice for setting/injecting object references within classes of the plugin within this framework?

My current plugin uses the 'static instance' approach but i feel this is out of place if we are following the PSR-4 structure. I found this page which discusses a the 'registry' and 'service-locator' pattern

https://wordpress.stackexchange.com/questions/70055/best-way-to-initiate-a-class-in-a-wp-plugin

In the current codebase, the Main class creates the Loader class, which drives the registration of all actions and filter. There is an AdminController, but in my case i want to create extra AdminControllers for specific actions. I'm wondering what would be the best way to pass the Loader object reference to these new AdminControllers in a clean manner.

My old bad plugin : https://github.com/emeraldjava/bhaawp
My new cleaner plugin : https://github.com/emeraldjava/bhaa_wordpress_plugin

Any advise would be appreciated.
Regards,
Paul

**Comment by davilera** [comment]
Hi! Sorry for the delay -- I created this repo as a side project and didn't pay much attention to it. How did you solve this issue in the end?

**Comment by emeraldjava** [comment]
Hi,

I took a visitor pattern approach as described here https://carlalexander.ca/polymorphism-wordpress-interfaces . My [Loader](https://github.com/emeraldjava/bhaa_wordpress_plugin/blob/master/src/utils/Loader.php) class is a bit different and i declare a [Loadable ](https://github.com/emeraldjava/bhaa_wordpress_plugin/blob/master/src/utils/Loadable.php) interface which my custom classes must implement to register their hooks and filter.

My [Main](https://github.com/emeraldjava/bhaa_wordpress_plugin/blob/master/src/Main.php) class does the heavy lifting still like this

` function registerObjects() {
        // register the front
        $controller = new front\Controller( $this->get_plugin_name(), $this->get_version());
        $controller->registerHooks($this->loader);
        // register the BHAA objects with support actions and filters.
        $adminController = new admin\AdminController( $this->get_plugin_name(), $this->get_version());
        $adminController->registerHooks($this->loader);
        $runnerAdminController = new admin\RunnerAdminController();
        $runnerAdminController->registerHooks($this->loader);
        $raceAdminController = new admin\RaceAdminController();
        $raceAdminController->registerHooks($this->loader);
        $leagueAdminController = new admin\LeagueAdminController();
        $leagueAdminController->registerHooks($this->loader);
        // register the core objects
        $raceCpt = new core\cpt\RaceCPT();
        $raceCpt->registerHooks($this->loader);
        $houseCpt = new core\cpt\HouseCPT();
        $houseCpt->registerHooks($this->loader);
        $leagueCpt = new core\cpt\LeagueCPT();
        $leagueCpt->registerHooks($this->loader);
        $connections = new core\Connections();
        $connections->registerHooks($this->loader);`

I think there could be a nice way of using Dependency Injection to register the classes but I haven't had time to investigate yet.
